seed = 5
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 22
cache = true
path = ":data/sait-submission"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"

[model]
d_main = 310
context_dropout = 0.21059390154453766
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 2
mixer_normalization = "auto"
dropout0 = 0.41871334166292035
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 42
frequency_scale = 0.03272235852111961
d_embedding = 62
lite = true

[optimizer]
type = "AdamW"
lr = 0.00012953811593024672
weight_decay = 0.0
