seed = 10
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 11
cache = true
path = ":data/sait-submission"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"

[model]
d_main = 240
context_dropout = 0.2404787602134526
d_multiplier = 2.0
encoder_n_blocks = 1
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.2763885024754076
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 81
frequency_scale = 0.010239119195579335
d_embedding = 37
lite = true

[optimizer]
type = "AdamW"
lr = 0.00014191444866850392
weight_decay = 0.0
