seed = 6
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 11
cache = true
path = ":data/sait"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"

[model]
d_main = 226
context_dropout = 0.07233000186923533
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 2
mixer_normalization = "auto"
dropout0 = 0.2921416889600971
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 52
frequency_scale = 0.024233931261830634
d_embedding = 45
lite = true

[optimizer]
type = "AdamW"
lr = 0.0003279945862296266
weight_decay = 0.0
