seed = 10
batch_size = 256
patience = 16
n_epochs = inf
context_size = 96

[data]
seed = 0
cache = true
path = ":data/sait-submission"
num_policy = "quantile"
cat_policy = "__null__"
y_policy = "standard"

[model]
d_main = 205
context_dropout = 0.11133000767060228
d_multiplier = 2.0
encoder_n_blocks = 0
predictor_n_blocks = 1
mixer_normalization = "auto"
dropout0 = 0.3264849999707765
dropout1 = 0.0
normalization = "LayerNorm"
activation = "ReLU"

[model.num_embeddings]
type = "PLREmbeddings"
n_frequencies = 16
frequency_scale = 0.012342187126691545
d_embedding = 40
lite = true

[optimizer]
type = "AdamW"
lr = 0.00030525750867072427
weight_decay = 2.5967576285315763e-05
