seed = 11

[data]
seed = 0
num_policy = "__null__"
cat_policy = "__null__"
cache = true
path = ":data/sait-submission"
y_policy = "standard"

[model]
iterations = 4000
early_stopping_rounds = 200
od_pval = 0.001
bagging_temperature = 0.2521395542071161
depth = 9
l2_leaf_reg = 9.051203102297846
leaf_estimation_iterations = 2
learning_rate = 0.025887250896045315
task_type = "CPU"
thread_count = 4

[fit]
logging_level = "Verbose"
